#Скачивание библиотек

In [139]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

#Шаг 1 работа с дата сетом

In [140]:
df = fetch_california_housing(as_frame=True).frame #добавила фрейм чтобы сразу был готовый дата сет

In [141]:
df.head(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611

In [142]:
df.info() #информация о дата сете

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [143]:
df.shape #количество строк и столбцов

(20640, 9)

In [144]:
df.isna().sum() #то есть нулей нет

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [145]:
df.describe() #среднее значение, минимальное, максимальное, стандартное отклонение

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [146]:
df.head(7)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992

#Шаг 2 формирую x и y

In [147]:
y=df['MedHouseVal']
x=df.drop('MedHouseVal',axis=1)

In [148]:
x.notna().count() #все ячейки заполнены

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

#Шаг 3 делю данные

In [149]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=78)

In [150]:
print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)

x_train shape: (16512, 8)
y_train shape: (16512,)
x_test shape: (4128, 8)
y_test shape: (4128,)

#Шаг 4 обучаю модель

In [151]:
model = LinearRegression()

In [152]:
model.fit(x_train, y_train)

LinearRegression()

#Шаг 5 делаю предсказания

In [153]:
y_pred=model.predict(x_test)

In [154]:
df_pred = pd.DataFrame({'Реальная цена': y_test.values,'Предсказание': y_pred})

In [155]:
df_pred['Ошибка']=abs(df_pred['Реальная цена']-df_pred['Предсказание']) #df_pred['Ошибка']=abs(y_test-y_pred) не подойдет из за различий в индаксах

In [156]:
df_pred

      Реальная цена  Предсказание    Ошибка
0             1.694      1.767510  0.073510
1             1.034      1.135998  0.101998
2             1.948      2.193235  0.245235
3             0.973      1.302198  0.329198
4             1.568      0.824370  0.743630
...             ...           ...       ...
4123          0.844      1.062088  0.218088
4124          1.474      1.740273  0.266273
4125          2.810      5.958835  3.148835
4126          2.680      1.981151  0.698849
4127          0.883      1.591261  0.708261

[4128 rows x 3 columns]

#Шаг 6 MAE и RMSE

In [157]:
mae=mean_absolute_error(y_test,y_pred) #просто средняя ошибка

In [158]:
RMSE=np.sqrt(mean_squared_error(y_test,y_pred)) #крупные ошибки получают большее отклонение за счет квадрата

In [159]:
mae

0.5330617042909688

In [160]:
RMSE #больше mae значит есть такие значения где она ошибалась очень сильно

np.float64(0.717051150625875)

In [161]:
y_m=y.mean()

In [162]:
print(mae/y_m) #ошибка в 25% является достаточно большой для жизненных задач

0.2576972271104626

#Шаг 7 проверяю переобучение

In [163]:
y_trainpr=model.predict(x_train)

In [164]:
mae_train=mean_absolute_error(y_train,y_trainpr)

In [165]:
mae_train

0.530901287078825

In [166]:
razrav=mae-mae_train
print(razrav) #это хороший показатель которые означанет что модель не переобучилась.она одинаково предсказывает и на тестовых данных и на тренировочных

0.0021604172121437726

#Шаг 8 веса

In [167]:
weight=model.coef_
print(weight)

[ 4.34657974e-01  9.13841299e-03 -1.04879358e-01  6.23887905e-01
 -6.88364751e-06 -4.70424357e-03 -4.21056656e-01 -4.33919077e-01]

In [168]:
x_col= x.columns

In [169]:
wei= pd.DataFrame({'название': x_col,'вес':weight})
print(wei)

     название       вес
0      MedInc  0.434658
1    HouseAge  0.009138
2    AveRooms -0.104879
3   AveBedrms  0.623888
4  Population -0.000007
5    AveOccup -0.004704
6    Latitude -0.421057
7   Longitude -0.433919

In [170]:
wei.sort_values('вес',ascending=False)

     название       вес
3   AveBedrms  0.623888
0      MedInc  0.434658
1    HouseAge  0.009138
4  Population -0.000007
5    AveOccup -0.004704
2    AveRooms -0.104879
6    Latitude -0.421057
7   Longitude -0.433919

Сильнее всего на стоимость недвижимости влияет количество спален. Это можно объяснить тем, что большее число спален обычно соответствует большей общей площади квартиры, а значит, и более высокой стоимости.

Я отсортировала признаки и выяснила, что в районах с более высоким уровнем дохода недвижимость стоит дороже — это вполне логично. Признаки, значения которых близки к нулю, практически не оказывают влияния на итоговый результат.

Кроме того, модель учитывает географический фактор: как правило, чем южнее расположен объект, тем выше его стоимость.

Ранее мы искали похожие векторы с помощью косинусной близости, а теперь определяем веса посредством скалярного произведения.

#Шаг 9
Моя модель в среднем ошибается на 53 тысячи долларов, что составляет около 26% от средней цены – в реальности маловато точности. Самые важные пункты, которые влияют на цену, – это количество спален и доход района (чем больше, тем дороже), а ещё география – где стоит дом, тоже решает. Переобучения нет-ошибки на обучающей и тестовой выборках почти одинаковые. Сейчас модель сама подбирает веса для признаков, а раньше мы просто сравнивали объекты через косинусную близость.